basicapp/urls.py
from django.urls import path
from basicapp import views

app_name='basicapp'

urlpatterns=[
  path('tracker/',views.tracker,name='tracker'),
  path('form_page/',views.form_name_view,name='form_page'),
  path('advisory/',views.advisory,name='advisory'),
  path('docbot/',views.docbot,name='docbot'),
]

basicforms/urls.py
from django.contrib import admin
from django.urls import path,include
from basicapp import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.index,name='index'),
    path('basicapp/',include('basicapp.urls')),
]

basicapp/models.py
from django.db import models

# Create your models here.

basicapp/forms.py
from django import forms
from django.core import validators
class FormName(forms.Form):
  name=forms.CharField()
  aadhar=forms.CharField(max_length=16)
  email=forms.EmailField()
  city=forms.CharField(max_length=64)
  date=forms.DateField()
  reason=forms.CharField(widget=forms.Textarea)
  botcatcher=forms.CharField(required=False,widget=forms.HiddenInput,validators=[validators.MaxLengthValidator(0)])

basicapp/views.py
from django.shortcuts import render
from . import forms
# Create your views here.
def index(request):
  return render(request,'basicapp/index.html')

def advisory(request):
  return render(request,'basicapp/advisory.html')

def docbot(request):
  return render(request,'basicapp/docbot.html')

def tracker(request):
  return render(request,'basicapp/tracker.html')

def form_name_view(request):
  form=forms.FormName()
  if request.method=='POST':
    form=forms.FormName(request.POST)
    if form.is_valid():
      print("Validation Success!")
      print("Name : "+form.cleaned_data['name'])
      print("Email : "+form.cleaned_data['email'])
      print("Text : "+form.cleaned_data['text'])
  return render(request,'basicapp/form_page.html',{'form':form})

templates/basicapp/docbot.html
<!--MUKUL-->
<!DOCTYPE html>
<html>
    <head>
        <title>COVID - Fight Against Corona</title>
         <link rel="shortcut icon" href="favicon.png">

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
      
             <script src="https://kit.fontawesome.com/a076d05399.js"></script>
 <!-- <style>
 @import url(https://fonts.googleapis.com/css?family=Open+Sans:400,600);
body {
  /* background:black; */
  color: #fff;
  font-family: 'Open Sans', sans-serif;
  margin: 0;
  padding: 0;
}
.flex {
  display: flex;
  justify-content: center;
  flex-flow: column;
  align-items: center;
  height: 100vh;
}

#result {
  font-size: 36px;
  color: #fff;
}

#ans {
  color: #fff;
  padding: 20px;
  font-size: 26px;
  background: transparent;
  border: 0; 
}

#ans:focus {
  outline: 0;
  outline-offset: 0;
}        </style> -->
    </head>
    <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <div class="text-left"><button class="btn btn-outline-success" type="button"> <a class="text-white-50" href="{%url 'basicapp:form_page' %}" > Get your Pass</a></button></div>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="{%url 'index' %}">What is Corona <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link active" href="{%url 'basicapp:advisory' %}">Advisory</a>
            <a class="nav-item nav-link" href="https://www.covid19india.org/">Tracker</a>
            <a class="nav-item nav-link" href="{%url 'basicapp:docbot' %}"><i class="fas fa-comment-alt"></i> Mr.DocBot</a>
          </div>
        </div>
        </nav>
 <div class="flex text-center bg-dark">
   <div class="jumbotron">
 	<p style="font-size: 40px;"><i class="	fas fa-robot"></i> Mr. DocBot </p></div>
  <div>
  </div>
  <div class="jumbotron text-center" id="result">
  </div>
  <div class="input-group mb-3 jumbotron input-group-lg"> 
    <div class="input-group-prepend">
      <span class="input-group-text" id="basic-addon3">Ask me anything!</span>
    </div>
    <input class="" type="text" id="ans" placeholder="Enter your name!" required/>
  </div>
</div>
<script src="https://code.jquery.com/jquery-3.0.0.js" integrity="sha256-jrPLZ+8vDxt2FnE1zvZXCkCcebI/C8Dt5xyaQBjxQIo=" crossorigin="anonymous"></script>
<script>
	var questions = [
    'What is your name?',
    'Let me tell you something about Covid19 !',
    'Coronaviruses are a large family of viruses that are known to cause illness ranging from the common cold to more severe diseases such as Middle East Respiratory Syndrome (MERS) and Severe Acute Respiratory Syndrome (SARS).',
    'Do you think you are affected?',
    'It depends on the virus, but common signs include respiratory symptoms, fever, cough, shortness of breath, and breathing difficulties. In more severe cases, infection can cause pneumonia, severe acute respiratory syndrome, kidney failure and even death.',
    'Please do not forget to wear a mask!',
    'are u wearing masks..?',
    ' Precautions of virus are... SOCIAL DISTANCING....WASH YOUR HANDS REGULARLY...WEAR YOUR MASKS...DO NOT GO OUT UNTILL NECESSARY',
    'OK,It was nice talking you :)'
];
var num = 0;

var inputBox = document.querySelector("#ans");
var output = document.querySelector("#result");
output.innerHTML = questions[num];

function showResponse() {
  var input = inputBox.value;
  if(inputBox.value == "") {
    
  }else {
  if(num == 0) {
    output.innerHTML = `Hii ${input}`;
    inputBox.value = "";
    inputBox.setAttribute("placeholder", "Wait for a secs");
    ++num;
    setTimeout(changeQuestion, 2000);
  } else if(num == 1) {
    inputBox.value = "";
    inputBox.setAttribute("placeholder", "Wait for a secs");
    ++num;
    setTimeout(changeQuestion, 2000);
  } else if(num == 2) {
    inputBox.value = "";
    inputBox.setAttribute("placeholder", "Wait for a secs");
    ++num;
    setTimeout(changeQuestion, 2000);
  } else if(num == 3) {
    inputBox.value = "";
    inputBox.setAttribute("placeholder", "Wait for a secs");
    ++num;
    setTimeout(changeQuestion, 2000);
  }else if(num == 4) {
    inputBox.value = "";
    inputBox.setAttribute("placeholder", "Wait for a secs");
    ++num;
    setTimeout(changeQuestion, 2000);
  }else if(num == 5) {
    inputBox.value = "";
    inputBox.setAttribute("placeholder", "Wait for a secs");
    ++num;
    setTimeout(changeQuestion, 2000);
  }
  }
}

function changeQuestion() {
  inputBox.setAttribute("placeholder", "Ask me !");
  output.innerHTML = questions[num];
  if(num == 6) {
    inputBox.style.display = "none";
  }
}

$(document).on('keypress', function(e) {
  if(e.which == 13) {
    showResponse();
  }
})

$( "#ans" ).focus();
</script>
<tr>
  <td>
  <div class="text-center bg-dark"> <br>
  <a href="#" class="btn btn-primary">FAQ</a>
  </div>
  </td>
  </tr>
  <tr class="bottom text-light">
  <td>
  </td>
  </tr>
  <div class="bg-dark">
  <tr class="text-light" >
  <td><footer> <div class="text-center text-white-50">&copy; Codeur Verset </div></footer>
  </div>
  </td>
  </tr>
  </table>
</body>
</html>

templates/basicapp/form_page.html
<!DOCTYPE html>
<html lang="en">
<head>
  {% load crispy_forms_tags %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>E-pass Form</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <div class="text-left"><button class="btn btn-outline-success active" type="button">Get your Pass</button></div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav ml-auto">
        <a class="nav-item nav-link" href="{%url 'index' %}">What is Corona <span class="sr-only">(current)</span></a>
        <a class="nav-item nav-link" href="{%url 'basicapp:advisory' %}">Advisory</a>
        <a class="nav-item nav-link" href="https://www.covid19india.org/">Tracker</a>
        <a class="nav-item nav-link" href="{%url 'basicapp:docbot' %}"><i class="fas fa-comment-alt"></i> Mr.DocBot</a>
        <a class="nav-item nav-link" href="#"></a>
      </div>
    </div>
  </nav><div class="jumbotron">
  <h1 class="text-center">To get your E-pass </h1>
  <h2 class="text-center">Fill out the form below!</h2></div>
  <div class="jumbotron bg-dark text-light">
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <div class="text-center">
      <button type="submit" class="btn btn-primary btn-lg btn-block">Apply</button></div>
    </form>
    
  </div>
  <tr>
    <td>
    <div class="text-center bg-dark"> <br>
    <a href="#" class="btn btn-primary">FAQ</a>
    </div>
    </td>
    </tr>
    <tr class="bottom text-light">
    <td>
    </td>
    </tr>
    <div class="bg-dark">
    <tr class="text-light" >
    <td><footer> <div class="text-center text-white-50">&copy; Codeur Verset </div></footer>
    </div>
    </td>
    </tr>
    </table>
</body>
</html>

templates/basicapp/index.html
<!--RACHIT-->
<!DOCTYPE html>
<html>
  {% load static %}
    <head>
        <title>COVID - Fight Against Corona</title>
        <link rel="shortcut icon" href="favicon.png">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>
        <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    </head>
    <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
      <div class="text-left"><button class="btn btn-outline-success" type="button"> <a class="text-white-50" href="{%url 'basicapp:form_page' %}" > Get your Pass</a></button></div>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav ml-auto">
          <a class="nav-item nav-link" href="{%url 'index' %}">What is Corona <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href="{%url 'basicapp:advisory' %}">Advisory</a>
          <a class="nav-item nav-link" href="https://www.covid19india.org/">Tracker</a>
          <a class="nav-item nav-link" href="{%url 'basicapp:docbot' %}"><i class="fas fa-comment-alt"></i> Mr.DocBot</a>
        </div>
      </div>
    </nav>
<div class="p-3 mb-2 bg-dark">
<p class="text-center" style="font-size: 150px; color:whitesmoke;"><i class="fas fa-viruses"></i>COVID-19</p>

<p class="text-center" style="font-size: 50px;color: yellow;" id="co">What is corona virus?</p>
<table border="0" width="100%">
<tr>
<td width="75%">
<div  style="margin-left: 20px">

<p class="text-light" style="font-size: 20px;">It is an infectious disease caused by a newly discovered coronavirus. Most people infected with the COVID-19 virus will experience mild to moderate respiratory illness and recover without requiring special treatment.  Older people, and those with underlying medical problems like cardiovascular disease, diabetes, chronic respiratory disease, and cancer are more likely to develop serious illness. The best way to prevent and slow down transmission is be well informed about the COVID-19 virus, the disease it causes and how it spreads. Protect yourself and others from infection by washing your hands or using an alcohol based rub frequently and not touching your face. The COVID-19 virus spreads primarily through droplets of saliva or discharge from the nose when an infected person coughs or sneezes, so it’s important that you also practice respiratory etiquette (for example, by coughing into a flexed elbow).</p>
</div>
</td>
<td width="25%">
<iframe style="margin-left: 10px" width="260" height="220"src="https://www.youtube.com/embed/BtN-goy9VOY?autoplay=1">
</iframe>
</td>
</tr>
</table>

<br>
<p class="text-center" id="what" style="font-size: 50px;color: yellow;">What You Can do?</p>
        <div class="container text-white-50" >
             <div class="box">
                  <div class="content">
                      <img class="img-fluid" src="https://1.bp.blogspot.com/-1hKrR5jY900/XmIhUeI8-jI/AAAAAAAAAOE/x0bKKjBgmNwOXN6RLEvhJ2FsuGCJH36ZwCLcBGAsYHQ/s1600/1583489237554.png">
                      <p>Wash Hands With Soap And Water After Touching Animals And Animal Products.</p>
                  </div>
            </div>  
            <div class="box">
                  <div class="content">
                      <img src="https://1.bp.blogspot.com/-kcoc6YV80gY/XmIhTRsrXxI/AAAAAAAAAOA/S9wd5xRfADoXEyQqLFIoyH689uEiGqGhwCLcBGAsYHQ/s1600/1583489222584.png">
                      <p>When Coughing And Sneezing Cover Mouth And Nose With Flexed Elbow OrTissue.</p>
                  </div>
            </div>
            <div class="box">
                  <div class="content">
                      <img src="https://1.bp.blogspot.com/-pTBqakXyOik/XmIhSJAZMxI/AAAAAAAAAN8/Ni10JzllNSAiG4f_5bPWWKBApAAaogpzwCLcBGAsYHQ/s1600/1583489207036.png">
                      <p>Avoid Travel If You Have A Fever And Cough.</p>
                  </div>
            </div>
            <div class="box">
                  <div class="content">
                      <img src="https://1.bp.blogspot.com/-B-ozcUOPfqY/XmIhO5VJBNI/AAAAAAAAAN0/WASo0h51IFMudRXKh0MVPJKDjNENA461QCLcBGAsYHQ/s1600/1583489192678.png">
                      <p>If You Have A Fever, Cough And Difficulty Breathing Seek Medical Care Early.</p>
                  </div>
            </div>
              <div class="box">
                  <div class="content">
                      <img src="https://1.bp.blogspot.com/-XfBsxpa5zvI/XmIhNriUnkI/AAAAAAAAANw/32YYZfsbqJMclHGB7wuXWSv-KKFPe9TGwCLcBGAsYHQ/s1600/1583489173735.png">
                      <p>If You Are Coughing or Sneezing, wear a Mask And Must Know how to use it and dispose of it properly.</p>
                  </div>
            </div>
              <div class="box">
                  <div class="content">
                      <img src="https://1.bp.blogspot.com/-esoCGSceykA/XmIhLNCon8I/AAAAAAAAANo/fWQvXmMCD_cYJrG4cT5UGsslEI64DIj1gCLcBGAsYHQ/s1600/1583489144169.png">
                      <p>Eat Only Wall-Cooked Food.</p>
                  </div>
            </div>
        </div>

        <div class="card bg-dark ">
          <div class="card-header p-3 mb-2 bg-primary text-white rounded">
              <H1 class="text-center"> E-Pass : </H1> 
          </div>
          <div class="card-body p-3 mb-2 bg-light text-dark rounded">
            <h5 class="card-title text-center">Important Note</h5>
            <p class="card-text">Due to current situation in the country, your co-operation is a must. Be a responsible citizen and only go out when it is very urgent.Only one pass per citizen will be issued in one week.</p>
            <div class="text-center">
            <a href="{%url 'basicapp:form_page' %}" class="btn btn-primary" >Get you Pass !</a>
          </div>
          </div>
        </div>
        <div class="card bg-dark ">
          <div class="card-header p-3 mb-2 bg-primary text-white rounded">
            <h1 class="text-center">PM  CARES FUND </h1>
          </div>
          <div class="card-body p-3 mb-2 bg-light text-dark rounded">
            <h5 class="card-title text-center">Important Note</h5>
            <div class="text-center">
            <p class="card-text">Account name: PM CARES</p>
            <p class="card-text">Account number: 2121PM20202</p>
            <p class="card-text">IFSC Code:      SBIN0000691</p>
            <p class="card-text">Bank:           State Bank of India , New Delhi</p>
            </div>
            <div class="text-center"> <br>
            <a href="#" class="btn btn-primary">Donate Now !</a>
          </div>
          </div>
        </div>
        <div>
          <p class="text-warning" style="font-size: 50px ;"><i class="fas fa-phone-alt"></i> Helpline Number:<a class="text-white-50" href="tel:+91-11-23978046"style="font-size: 50px;">+91-11-23978046</a></p>
          <br>
          <p class="text-warning" style="font-size: 50px;"><i class="fas fa-phone-alt"></i> Toll free No:<a class="text-white-50" href="tel:1075"style="font-size: 50px;">1075</a></p>
        </div>
        <br>
        <br>
        <table border="0" width="100%" height="150px" bgcolor="#232F3E">
          <tr>
            <td>
</td>
</tr>
<tr class="bottom text-white-50">
  <!-- <td>-- Rachit Goyal (Topper) -->
    </td>
  </tr>
<tr>
  <td>
    <div class="text-center"> <br>
      <a href="#" class="btn btn-primary">FAQ</a>
    </div>
      </td>
</tr>
<tr class="bottom text-light">
  <td>
    </td>
  </tr>
  <tr class="text-light" >
    <td><footer> <div class="text-center">&copy; Codeur Verset </div></footer>
    
    </td>
  </tr>
    </table>
  </div>
    </body>
</html>

templates/basicapp/tracker.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Advisory</title>
  <link rel="shortcut icon" href="favicon.png">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/a076d05399.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
<div class="text-left"><button class="btn btn-outline-success" type="button"> <a class="text-white-50" href="{%url 'basicapp:form_page' %}" > Get your Pass</a></button></div>

<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
  <div class="navbar-nav ml-auto">
    <a class="nav-item nav-link" href="{%url 'index' %}">What is Corona <span class="sr-only">(current)</span></a>
    <a class="nav-item nav-link " href="{%url 'basicapp:advisory' %}">Advisory</a>
    <a class="nav-item nav-link active" href="{%url 'basicapp:tracker' %}">Tracker</a>
    <a class="nav-item nav-link" href="{%url 'basicapp:docbot' %}"><i class="fas fa-comment-alt"></i> Mr.DocBot</a>
  </div>
</div>
</nav>
<div class="jumbotron"> 
  <h1>Hello this is Tracker page!</h1>
  <h2>Under Construction</h2> </div>

  <br>
  <br>
  <table border="0" width="100%" height="150px" bgcolor="#232F3E">
    <tr>
      <td>
</td>
</tr>
<tr class="bottom text-white-50">
<!-- <td>-- Rachit Goyal (Topper) -->
</td>
</tr>
<tr>
<td>
<div class="text-center"> <br>
<a href="#" class="btn btn-primary">FAQ</a>
</div>
</td>
</tr>
<tr class="bottom text-light">
<td>
</td>
</tr>
<tr class="text-light" >
<td><footer> <div class="text-center">&copy; Codeur Verset </div></footer>

</td>
</tr>
</table>
</body>
</html>